[package]
name = "rustls_echo"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0"
webpki = "0.22"
webpki-roots = "0.25"
clap = { version = "4.5.37", features = ["derive"] }
anyhow = "1.0"
