[package]
name = "threaded_client"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
flexi_logger = "0.29.2"
log = "0.4.22"
